<?php

/**
 * @Filename: class-nh_faq.php
 * @Description:
 * @User: NINJA MASTER - Mustafa Shaaban
 * @Date: 5/10/2023
 */


namespace NH\APP\MODELS\FRONT\MODULES;

use NH\APP\CLASSES\Nh_Module;
use NH\APP\CLASSES\Nh_Post;
use WP_Post;


/**
 * Description...
 *
 * @class Nh_Faq
 * @version 1.0
 * @since 1.0.0
 * @package NinjaHub
 * @author Mustafa Shaaban
 */
class Nh_Faq extends Nh_Module
{
    public array $meta_data = [
        'cover',
    ];
    public array $taxonomy  = [];

    public function __construct()
    {
        parent::__construct('faq');
    }

    /**
     * Description...
     *
     * @param \WP_Post $post
     * @param array    $meta_data
     *
     * @version 1.0
     * @since 1.0.0
     * @package NinjaHub
     * @author Mustafa Shaaban
     * @return \NH\APP\CLASSES\Nh_Post
     */
    public function convert(WP_Post $post, array $meta_data = []): Nh_Post
    {
        return parent::convert($post, $this->meta_data); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    protected function actions($module_name): void
    {
        // TODO: Implement actions() method.
    }

    /**
     * @inheritDoc
     */
    protected function filters($module_name): void
    {
        // TODO: Implement filters() method.
    }

    /**
     * Description...
     * @version 1.0
     * @since 1.0.0
     * @package NinjaHub
     * @author Ahmed Gamal
     * @return string
     */
    public function breadcrumb(): string
    {
        global $post;
        $html = '<ul class="breadcrumbs">';

        $html .= '<li><a href="' . home_url() . '">'.get_the_title(get_option('page_on_front')).'</a></li>';
        if (is_archive()) {
            $post_type = get_post_type();
            $post_type_obj = get_post_type_object($post_type);
            $html .= '<li>&raquo;</li>';
            $html .= '<li>' .  the_archive_title('<span class="page-title">', '</span>') . '</li>';
        } elseif (is_single()) {
            $post_type = get_post_type($post);
            $html .= '<li><a href="' . get_post_type_archive_link($post_type) . '"></a></li>';
            $html .= '<li>&raquo;</li>';
            $html .= '<li><span class="page-title">' . get_the_title() . '</span></li>';
        } elseif (is_page() && !is_front_page()) {
            $html .= '<li>&raquo;</li>';
            $html .= '<li><span class="page-title">' . get_the_title() . '</span></li>';
        }
        $html .= '</ul>';
        echo $html;
    }
}
